### PR TITLE
UDP support and fixes

### PR DESCRIPTION
**Pull request by Jonplussed**
This greatly simplifies the `hsyslog` API, removing much redundant code and documentation in preparation for a major release. It also fixes an error that treats `Facility` and `Priority` values as bit-masks, when only `Option` and `PriorityMask` are bit-masks. The practical effect of this is that only one `Facility`/`Priority` may be logged to with each message.

### CODE REVIEW

**Comment by Jonplussed** [comment]
@k-bx @qrilka These seem like drastic changes, but are really only three:

1. any `[Facility]` and `[Priority]` arguments for logging are now `Facility` and `Priority`.
2. removed `withSyslogTo` and related functions, which were totally unnecessary and only served to clutter the API
3. removed documentation of C functions that were cut/paste from the GNU libc docs; why maintain the same documentation twice?

**Comment by k-bx** [comment]
Looks good

**Comment by qrilka** [comment]
do we plan to push it upstream?

**Comment by qrilka** [comment]
LGTM

**Pull request merged**
