### PR TITLE
prevent identifier garbage collection

### PR DESCRIPTION
**Pull request by Jonplussed**
The solution is manual memory management! :sob: It's not too bad— we allocate the identifier string when we open the syslog connection and deallocate when we close the connection.

Some background: there are safe and unsafe versions of the main syslog functions: `openSyslog`, `closeSyslog`, and `syslog`. Previously, the only difference was that the safe syslog function was guaranteed to be bracketed. Now, the difference is wider.

The safe syslog functions are still as safe— the managed identifier string is handled by bracketing. The unsafe functions, sadly, are more unsafe. Upon `syslogOpenUnsafe`, the identifier is stored in an `MVar` via...
```haskell
{-# NOINLINE identRef #-}
identRef :: MVar CString
identRef = unsafePerformIO newEmptyMVar
```
...which is emptied when `closeSyslogUnsafe` is called.

The safe and unsafe versions meet at `openSyslogWithIdent` and `closeSyslogWithIdent`— from there functionality is shared.

### CODE REVIEW

**Comment by Jonplussed** [comment]
@k-bx the solution is definitely curious. I'm going to look into `System.Process` to create some more robust tests.

**Comment by Jonplussed** [comment]
@rowanblush any suggestions for how this might be improved?

**Comment by k-bx** [comment]
Unfortunately don't have too much time going into details here, so let's be happy with anything that works for now :)

**Comment by Jonplussed** [comment]
@k-bx wait before making the change to AdServer; I realized something I need to try. I'm out running an errand but will be back soon.

**Comment by k-bx** [comment]
@Jonplussed no rush, I'm not merging develop->master yet

**Pull request merged**
