### PR TITLE
add support for facilities, options, and priorities and improve performance

### PR DESCRIPTION
**Pull request by Jonplussed**
This brings the hsyslog API into feature parity with the libc implementation, including support for options, priority masking, and default and per-message facilities.

### CODE REVIEW

**Comment by Jonplussed** [comment]
@rowanblush @k-bx hsyslog is ready to rumble!

**Comment by Jonplussed** [comment]
I forgot to mention: if you have any ideas for robust tests, I'd love to hear them. The current (and only) test in `test/Main.hs` is embarrassing.

**Comment by k-bx** [comment]
Great job! Hopefully we can also figure out the dgram-related functionality discussed in Pivotal :+1:

**Comment by Jonplussed** [comment]
@k-bx Thank you! :smile: I actually don't think that functionality is required— I believe (though I'll have to double-check) that `/dev/log` is opened as a datagram socket by default. In that case, hsyslog should fall back to datagram automatically.

**Comment by Jonplussed** [comment]
@k-bx @rowanblush I also added some optional API improvements in a [separate branch](https://github.com/ThoughtLeadr/hsyslog/compare/add-facility-support...ThoughtLeadr:friendlier-api). I think the safety it provides is important, but as it's not part of the original request, I haven't included it in this pull request. Would love to know what you think, though.

**Comment by k-bx** [comment]
@Jonplussed yeah, that one looks nice as well

**Comment by Jonplussed** [comment]
Okay; I'll merge it into the PR. I can always roll back if needed.

**Comment by rowanblush** [comment]
Can't you escape the bracketing function with `withSyslog config return`?

**Comment by Jonplussed** [comment]
@rowanblush daaamn; nice catch!

**Comment by Jonplussed** [comment]
@rowanblush fixed! :sweat_smile:

**Comment by rowanblush** [comment]
On testing&mdash;

* You could rely on QuickCheck `Arbitrary` instances passing in lots of long and complicated strings only to make sure no exceptions are raised (including OOM). Not blowing up is an excellent property.
* Reading the logging output (probably by forking a thread to tail the log on a shell) and checking for well-orderedness of messages in a multi-threaded environment, or for round-trip stability of serialized values, that sort of thing.

I don't have anything else though, so :+1: from me, merge if @k-bx is also good with it.

**Comment by Jonplussed** [comment]
@rowanblush I can at least add the first quickly, and attempt variations of the latter until something satisfactory emerges. Thanks!

**Comment by Jonplussed** [comment]
@k-bx good to merge? If so, I'll do this now.

**Comment by k-bx** [comment]
@Jonplussed yes please

**Pull request merged**
